.TH rpmreaper 1
.SH NAME
rpmreaper \- A tool for removing unnecessary packages from system

.SH SYNOPSIS
\fBrpmreaper\fR [\fB-lvh\fR] [\fB-r\fR \fIroot\fR] [\fIlimit\fR]

.SH DESCRIPTION
rpmreaper is a simple ncurses application with a mutt-like interface that
allows removing unnecessary packages and their dependencies from the system.

.SH OPTIONS
.TP 8
\fB-l\fR
List packages matching \fIlimit\fR, or all installed if not specified.
.TP 8
\fB-v\fR
Verbose listing. 
.TP 8
\fB-r\fR \fIroot\fR
Specify root directory (default is \fB/\fR).
.TP 8
\fB-h\fR
Print help.

.PP
A \fIlimit\fR can be specified to limit the list of displayed packages. The
syntax is described in the \fBSEARCH EXPRESSIONS\fR section.

.SH KEYS
.TP 8
\fBUP, DOWN, LEFT, PGUP, PGDOWN, HOME, END, TAB, BTAB, h, j, k\fR
Move cursor.
.TP 8
\fB[, ], <, >\fR
Scroll screen.
.TP 8
\fBd\fR
Mark the highlighted package to be removed.
.TP 8
\fBD\fR
Mark the highlighted package to be removed even when there are unmarked
packages depending on the package.
.TP 8
\fBE\fR
Recursively mark the highlighted package and unmarked packages depending on the
package to be removed.
.TP 8
\fBu\fR
Unmark the highlighted package.
.TP 8
\fBU\fR
Unmark the highlighted package even when some dependencies are marked to be removed.
.TP 8
\fBI\fR
Recursively unmark the highlighted package and marked packages that the package
depends on. Packages where a choice has to be made to satisfy a dependency will
be left with the \fBb\fR flag and the missing packages should be unmarked
manually.
.TP 8
\fBr, R\fR
Show/hide subtree of packages that are required by (with \fBR\fR also indirectly) the highlighted package.
.TP 8
\fBb, B\fR
Show/hide subtree of packages that require (with \fBB\fR also indirectly) the
highlighted package.
.TP 8
\fBo\fR
Sort packages by name, flags or size.
.TP 8
\fBl\fR
Limit the list of displayed packages. Uses the \fBSEARCH EXPRESSION\fR syntax.
.TP 8
\fB/, ?\fR
Search in the package list. Uses the \fBSEARCH EXPRESSION\fR syntax.
.TP 8
\fBn\fR
Search for next package.
.TP 8
\fBN\fR
Search for next package in the opposite direction.
.TP 8
\fBi\fR
Run \fBrpm -qil | less\fR on the highlighted package. If environment variable
\fBPAGER\fR is set, its value is used instead of \fBless\fR.
.TP 8
\fBc\fR
Run \fBrpm -e\fR on marked packages.
.TP 8
\fBC\fR
Run \fBrpm -e --nodeps\fR on marked packages.
.TP 8
\fBq\fR
Ask to remove marked packages and quit. If the answer is no, the list of
marked packages will be written to \fBstderr\fR.
.TP 8
\fBx\fR
Exit immediately.
.TP 8
\fBF1\fR
Run \fBman rpmreaper\fR.
.TP 8
\fB^R\fR
Reload package list.
.TP 8
\fB^L\fR
Redraw screen.

.SH PACKAGE FLAGS
.TP 8
\fBL\fR
Leaf, no package depends on the package.
.TP 8
\fBl\fR
Partial leaf, some packages may depend on the package and removing the package
may remove \fBL\fR/\fBl\fR flag from other packages.
.TP 8
\fBD\fR
Marked to be removed.
.TP 8
\fBo\fR
Part of a dependency cycle.
.TP 8
\fBB\fR
Missing dependencies.
.TP 8
\fBb\fR
Some packages required by the package are marked to be removed.

.SH SEARCH EXPRESSIONS

Search expression is a regular expression which can be optionally extended with
roughly mutt-esque directives for matching package flags. Overall search
expression syntax looks like this:

{[!]~\fIflags\fR }[\fIregexp\fR]

Recognized flags are described in the section \fBPACKAGE FLAGS\fR. Search
expression matches a package, if the following three conditions hold: any of
the flags specified in \fB~\fR directives is set; none of the flags specified
in \fB!~\fR directives are set; and the specified regular expression matches
the \fBn-v-r[.a]\fR string of the package.

Examples:

.TP 8
\fB~Ll i386$\fR
Match all leaf and partial leaf i386 packages.
.TP 8
\fB!~D perl\fR
Match all perl packages except those marked for deletion.

.SH SEE ALSO
.BR rpm (8)

.SH AUTHORS
Miroslav Lichvar <mlichvar@redhat.com>
.br
Petr Machata <pmachata@redhat.com>
